# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/coarsetime"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/finder"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/gomod"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/gorm-datatype"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/jwt"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/password"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/pool"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/random"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/rogu"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/sitemap"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/strong"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/ "
    schedule:
      interval: "daily"
