version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/bunpgd"
      - "/debugger"
      - "/pyrokinesis"
      - "/random"

      - "/coarsetime"
      - "/buffer"
      - "/jwt"
      - "/password"
      - "/strong"
      - "/strutils"
    schedule:
      interval: "daily"
