//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"log"
	"os"

	"go.x2ox.com/sorbifolia/http/status"
)

func main() {
	buf := new(bytes.Buffer)
	buf.WriteString(tpl)
	buf.WriteString("var table = [412][]byte{")

	needLineBreak := false

	for i := 0; i < 412; i++ {
		if needLineBreak {
			buf.Write([]byte("\n\t"))
		}

		s := status.Status(i + 100)
		str := s.String()
		if str == "" {
			if needLineBreak {
				buf.WriteString("nil,")
			} else {
				buf.WriteString(" nil,")
			}
			needLineBreak = false
			continue
		}

		if !needLineBreak {
			buf.Write([]byte("\n\t"))
		}
		buf.WriteString(fmt.Sprintf("[]byte(\"%d %s\"),", s, str))
		needLineBreak = true
	}

	buf.WriteString("\n}\n")

	if err := os.WriteFile("bytes.go", buf.Bytes(), 0660); err != nil {
		log.Fatal(err)
	}
}

// 默认 100 开始, 511 结束( 0 - 411)
var table = [412][]byte{
	[]byte(fmt.Sprintf("%d %s", 1, "")),
}

const tpl = `package status

// Code generated by go run status_gen.go; DO NOT EDIT.
// See status_gen.go for more information about these tables.

`
