name: automerge
on:
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies"
          MERGE_REMOVE_LABELS: "dependencies"
          MERGE_METHOD: "squash"
          MERGE_DELETE_BRANCH: "true"
          MERGE_FILTER_AUTHOR: "dependabot"