name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Read the markdown template
        uses: juliangruber/read-file-action@v1
        id: template
        with:
          path: "./.github/templates/greetings.md"

      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: ${{ steps.template.outputs.content }}
