name: Lint
on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_MODULES: >-
    ./buffer/... ./bunpgd/... ./coarsetime/... ./debugger/... ./jwt/...
    ./password/... ./pyrokinesis/... ./random/... ./strong/... ./strutils/...

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.work

      - run: diff -u <(echo -n) <(gofmt -d .)
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout=5m -- ${{ env.GO_MODULES }}
