name: Test
on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_MODULES: >-
    ./buffer/... ./bunpgd/... ./coarsetime/... ./debugger/... ./jwt/...
    ./password/... ./pyrokinesis/... ./random/... ./strong/... ./strutils/...

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.work

      - run: go test $GO_MODULES
      - run: go test -race -cover -coverprofile="coverage.txt" $GO_MODULES
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
